import { useState } from 'react';
import { Bug, Check, ChevronDown, ChevronUp, Copy, Crown, Flag, LogOut, Mic, MicOff, Play, RotateCcw, UserPlus, Volume2, Waves, X } from 'lucide-react';
import type { CharacterOption, ClientMessage, MicStatus, Party } from '../../shared/protocol';
import type { VoiceState } from '../client/useVoice';
import { Avatar, IconButton, Modal } from './primitives';

const labels: Record<MicStatus, string> = { unchecked: '尚未检查麦克风', checking: '正在检查麦克风', denied: '麦克风权限未开启', missing: '没有可用麦克风', silent: '尚未检测到声音', connecting: '语音连接中', disconnected: '语音已断开', muted: '麦克风已静音', ok: '语音正常', error: '音频故障' };
interface Props { party: Party | null; selfId: string; characters: CharacterOption[]; connected: boolean; minPartySize: number; send: (message: ClientMessage) => boolean; voice: VoiceState & { enable: (deviceId?: string) => void; toggleMute: () => void }; onInvite: () => void; notify: (message: string) => void; onDialog: (value: boolean) => void; debugReport: () => Promise<string> }
export function PartyPanel({ debugReport, party, selfId, characters, connected, minPartySize, send, voice, onInvite, notify, onDialog }: Props) {
  const [expanded, setExpanded] = useState(false); const [confirmLeave, setConfirmLeave] = useState(false); const [confirmMicless, setConfirmMicless] = useState(false);
  const leader = party?.leaderId === selfId; const me = party?.members.find(member => member.id === selfId);
  // The leader has no ready state; the count and the heading only cover the other members.
  const others = party?.members.filter(member => member.id !== party.leaderId) || [];
  const readyCount = others.filter(member => member.ready).length;
  const canStart = !!party && party.members.length >= minPartySize && party.members.every(member => member.online && member.ready);
  const live = !!party && party.phase !== 'forming';
  function confirm(value: boolean) { setConfirmLeave(value); onDialog(value); }
  function micless(value: boolean) { setConfirmMicless(value); onDialog(value); }
  async function share() {
    if (!party) return;
    const url = new URL(window.location.href); url.search = ''; url.searchParams.set('invite', party.inviteCode); url.hash = '';
    try { await navigator.clipboard.writeText(url.href); notify('邀请链接已复制，发给朋友就能加入。'); } catch { notify(`复制邀请链接：${url.href}`); }
  }
  return <section className={`party-panel ${party ? 'has-party' : ''} ${expanded ? 'expanded' : ''}`} aria-label="我的队伍">
    {!party ? <div className="party-empty"><div><span className="challenge-mark"><Waves size={18} /></span><h2>荡秋千，缺个搭子</h2><p>组个队，一起越过这片山谷。</p></div><button className="button primary" data-testid="create-party" disabled={!connected} onClick={() => { send({ type: 'party.create' }); setExpanded(true); }}><UserPlus size={18} />召集队友</button></div> : <>
      <header className="party-heading"><button className="party-heading-toggle" onClick={() => setExpanded(value => !value)} aria-expanded={expanded}><span className="challenge-mark"><Waves size={18} /></span><span><strong>{live ? '绳子挑战 · 荡秋千' : '一起荡秋千'}</strong><small>{live ? party.phase === 'won' ? '挑战完成' : '队伍语音保持连接' : `${party.members.length}/${party.maxMembers} 人 · ${others.length ? `${readyCount}/${others.length} 位队员准备好了` : '等队员加入'}`}</small></span>{expanded ? <ChevronUp size={17} /> : <ChevronDown size={17} />}</button></header>
      <div className="party-details"><div className="party-members">{party.members.map(member => <div className="member-row" key={member.id}><Avatar player={member} characters={characters} /><div className="player-identity"><strong>{member.nickname}{member.id === selfId && <span className="you-label">我</span>}{member.id === party.leaderId && <Crown size={13} aria-label="队长" />}</strong><span className={member.mic.status === 'ok' ? '' : 'mic-warning'} title={member.mic.message}>{!member.online ? '已掉线，保留席位中' : member.micless ? '不开麦参加，队友听不到 TA' : member.mic.message || labels[member.mic.status]}</span></div>{member.id === party.leaderId ? <span className={`ready-indicator ${member.ready ? 'is-ready' : ''}`}>{member.ready ? member.micless ? <MicOff size={16} aria-label="未开麦" /> : <Mic size={16} aria-label="麦克风正常" /> : <MicOff size={16} aria-label={labels[member.mic.status]} />}</span>
        : <span className={`ready-indicator ${member.ready ? 'is-ready' : ''}`}>{member.ready ? <>{member.micless ? <MicOff size={14} aria-label="未开麦" /> : <Check size={14} />}已准备</> : member.mic.status === 'ok' ? '未准备' : <MicOff size={16} aria-label={labels[member.mic.status]} />}</span>}</div>)}</div>
      <div className="voice-controls"><div className="mic-message"><span className={`mic-symbol ${voice.report.status === 'ok' ? 'is-good' : ''}`}><Mic size={16} /></span><span>{voice.report.message}</span><div className="volume-meter" role="meter" aria-label="麦克风音量" aria-valuemin={0} aria-valuemax={100} aria-valuenow={Math.round(voice.level * 100)}><i style={{ transform: `scaleY(${Math.max(0.08, voice.level)})` }} /></div></div>
        <div className="voice-buttons"><button className="button subtle" data-testid="mic-check" disabled={!connected || voice.report.status === 'checking'} onClick={() => voice.enable()}>{voice.playbackBlocked ? <Volume2 size={15} /> : <Mic size={15} />}{voice.playbackBlocked ? '开启声音' : voice.report.status === 'ok' ? '重新检查' : '开启 / 检查麦克风'}</button>{voice.report.published && <IconButton icon={voice.report.status === 'muted' ? Mic : MicOff} label={voice.report.status === 'muted' ? '取消静音' : '麦克风静音'} onClick={voice.toggleMute} />}</div>
        {voice.devices.length > 1 && <label className="device-select">麦克风<select aria-label="选择麦克风" value={voice.deviceId} onChange={event => voice.enable(event.target.value)}>{voice.devices.map((device, index) => <option key={device.deviceId} value={device.deviceId}>{device.label || `麦克风 ${index + 1}`}</option>)}</select></label>}
      </div>
      {!live && <p className="ready-note">{leader ? me?.micless ? '已选择不开麦出发。麦克风检查通过后会自动恢复语音。' : '队长无需准备：麦克风检查通过、队员全部准备后即可出发。' : me?.micless ? '已不开麦准备。麦克风检查通过后会自动改为语音准备。' : me?.autoReady ? '检测到声音后会自动准备；安静时仍保持准备。' : '已关闭自动准备。检查通过后，点击准备即可。'}</p>}
      <div className="party-secondary"><button className="text-button" onClick={() => void share()}><Copy size={14} />分享邀请</button>{leader && !live && <button className="text-button" onClick={onInvite}><UserPlus size={14} />邀请玩家</button>}<button className="text-button muted" onClick={() => confirm(true)}>{leader ? <X size={14} /> : <LogOut size={14} />}{leader ? '解散' : '退出'}</button></div></div>
      {!live && (!me?.ready || ['denied', 'missing', 'error', 'disconnected'].includes(voice.report.status)) && <div className="mic-fallback">
      {!me?.ready && voice.report.status !== 'ok' && voice.report.status !== 'checking' && <button className="text-button micless-entry" data-testid="ready-without-mic" disabled={!connected} onClick={() => micless(true)}><MicOff size={14} />麦克风用不了？{leader ? '不开麦出发' : '不开麦准备'}</button>}
      {['denied', 'missing', 'error', 'disconnected'].includes(voice.report.status) && <button className="text-button micless-entry" data-testid="voice-debug-report" onClick={() => void debugReport().then(code => notify(`调试报告已发送，编号 ${code}，把编号告诉维护者即可。`), error => notify(error instanceof Error ? error.message : '调试报告发送失败'))}><Bug size={14} />发送调试报告</button>}
      </div>}
      <div className="party-actions">{!live ? <>
        {!leader && <button className={`button ${me?.ready ? 'subtle' : 'secondary'}`} data-testid={me?.ready || me?.autoReady ? 'cancel-ready' : 'ready'} disabled={!connected || (!me?.ready && !me?.autoReady && voice.report.status !== 'ok')} onClick={() => send({ type: 'party.ready', ready: !(me?.ready || me?.autoReady) })}>{me?.ready ? <Check size={17} /> : <Mic size={17} />}{me?.ready ? '取消准备' : me?.autoReady ? '取消自动准备' : '准备'}</button>}
        {leader ? <button className="button primary" data-testid="start-game" disabled={!connected || !canStart} title={!canStart ? `至少 ${minPartySize} 人，队员全部准备且你的麦克风检查通过后出发` : '开始荡秋千'} onClick={() => send({ type: 'party.start' })}><Play size={16} />出发</button> : <span className="waiting-leader">等队长出发</span>}
      </> : <>{leader && <button className="button secondary" onClick={() => send({ type: 'party.restart' })} disabled={!connected}><RotateCcw size={16} />再来一次</button>}<button className="button subtle" onClick={() => send({ type: 'party.return' })} disabled={!connected}><Flag size={16} />回到大厅</button></>}</div>
    </>}
    <Modal open={confirmMicless} onOpenChange={micless} title={leader ? '不开麦也出发？' : '不开麦也准备？'} description="荡秋千要靠语音喊队友配合，建议先试试开启麦克风。不开麦时仍能听到队友，但队友听不到你，队伍里会显示你未开麦。"><div className="dialog-actions"><button className="button subtle" onClick={() => { micless(false); voice.enable(); }}><Mic size={15} />再试试麦克风</button><button className="button primary" data-testid="confirm-micless" disabled={!connected} onClick={() => { send({ type: 'party.ready', ready: true, withoutMic: true }); micless(false); }}>{leader ? '不开麦出发' : '不开麦准备'}</button></div></Modal>
    <Modal open={confirmLeave} onOpenChange={confirm} title={leader ? '解散这支队伍？' : '离开这支队伍？'} description={live ? '当前挑战将结束，所有队员回到大厅。' : '队伍语音会断开，仍然可以在公园里和大家聊天。'}><div className="dialog-actions"><button className="button subtle" onClick={() => confirm(false)}>继续留在队伍</button><button className="button danger" onClick={() => { send({ type: leader ? 'party.disband' : 'party.leave' }); confirm(false); }}>{leader ? '确认解散' : '确认退出'}</button></div></Modal>
  </section>;
}
